### ISSUE TITLE
Add option not to produce DLA in SIMQSO

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#327]
In SIMQSO, is it possible to have an option not to add DLAs?
I.e. have the Lyman-alpha forest but not the DLAs.

**Comment by moustakas** [comment]
DLAs have not yet been connected to the simqso spectra and in `lya_spectra.get_spectra` (which still uses `templates.QSO`) the default is `add_dlsa=False`.

**Comment by londumas** [comment]
Are you sure? This really looks like a DLA to me:
![capture d ecran de 2018-02-26 17-35-20](https://user-images.githubusercontent.com/3166436/36703983-75f04d90-1b1b-11e8-9bc3-5cdde5471a8d.png)

Using:
```
import matplotlib.pyplot as plt
import numpy as np
from desisim.templates import SIMQSO
CRVAL1 = 2.6534
CDELT1 = 0.0001
NBLL   = 13637
wave = 10**(CRVAL1+np.arange(NBLL)*CDELT1)
nqso = 10
tflux, twave, tmeta = SIMQSO().make_templates(nmodel=nqso, zrange=(0., 10.), seed=1234, lyaforest=True, nocolorcuts=True)

for i in range(nqso):
    plt.plot(twave/(1.+tmeta['REDSHIFT'][i]),tflux[i])
    plt.xlabel(tmeta['REDSHIFT'][i])
    plt.grid()
    plt.show()
```

**Comment by moustakas** [comment]
I was actually not aware of this!  It might be worth posting a question / issue at the simqso repo --
  https://github.com/imcgreer/simqso/issues

Or, if we don't get a response, we may need to fork simqso to desihub and do our own development.

**Comment by andreufont** [comment]
@londumas @moustakas @alxogm - this has probably been fixed, right? Otherwise we would have seen this when running quickquasars... although it might not have been fixed in quickspectra?

**Comment by moustakas** [comment]
Poking around `quickquasars` and `templates.SIMQSO` it doesn't look like the simqso-based DLAs have been were turned off (although we know how to based on the instructions in https://github.com/imcgreer/simqso/issues/23).

However, it looks like `lyaforest=False` in `quickquasars`, so this issue would never turn up.

**Comment by londumas** [comment]
This issue is only when using the internal Lya-forest of desisim.SIMQSO. So it doesn't impact quickquasar.

**Comment by alxogm** [comment]
As said above, this is not affecting quickquasars. But I ran the same commands that appear in the original post above and still there appears DLAs. And I was looking to code lines in quickspectra and desisim.templates  that resemble imcgreer instructions but haven't find them, maybe it is somewhere else... so I'm not sure yet if  this is still an issue in other applications...

**Comment by julienguy** [comment]
DLAs are part of the IGM transmission simulated in SIMQSO:
desisim.templates.SIMQSO._make_simqso_templates calls
simqso.sqmodels.get_BossDr9_model_vars which calls
simqso.hiforest.IGMTransmissionGrid(...,forestModels['Worseck&Prochaska2011'],...)
and this model has DLAs.

Instead of modifying simqso for this purpose,
I suggest we never call desisim.templates.SIMQSO.make_templates with the option lyaforest=True,
and same for desisim.templates.QSO.make_templates.

This is how it is done where we need it (for desisim.templates.SIMQSO):
 - in desisim.scripts.quickquasars
 - in desitarget.mock.mockmaker.QSOMaker.make_spectra

I propose we simply remove this option from desisim.templates.SIMQSO.make_templates and desisim.templates.QSO.make_templates.

**Comment by andreufont** [comment]
Hi @julienguy - for the needs of the Lyman alpha working group, I agree with you that we do not need to modify SIMQSO. 

However, I'm not sure we want to remove the lyaforest option from desisim.templates.SIMQSO.make_templates and desisim.templates.QSO.make_templates, since sometimes you just want to simulate a quasar without the need of a transmission file. For instance when generating simulated spectra to test Redrock, where you don't really care about 3D correlations and it is nice to have code that generates reasonably looking Lya forest on the fly. I guess that's where this issue comes from, since it was raised by @londumas.

@londumas - if you wanted to have SIMQSO spectra with (1D) Lya forest and no DLAs, it would be trivial to do. Instead of asking SIMQSO to add Lyman alpha (that would also add DLAs), you can add the Lyman alpha later on like we do for QSO.make_templates, where we call the 1D code that I added to desisim. It would make the SIMQSO.make_templates code a bit more convoluted though.

**Comment by londumas** [comment]
Hi @andreufont, I stepped upon this issue when testing redrock and its systematic shift due to the Lyman-alpha forest.I don't need this to be corrected anymore since I can use quickquasar.

**Comment by moustakas** [comment]
I agree with @andreufont that the `lyaforest` option in `SIMQSO.make_templates` should not be *removed*.  If anything, you could change the default to `False`, but since `desisim/bin/quickquasars` and `desitarget.mock.mockmaker.QSOMaker.make_spectra` already set this to `False` then everything should be fine.

**Comment by moustakas** [comment]
It sounds like this issue was resolved some time ago so I'm closing it; please reopen if not.
